# Generated by Django 3.0.5 on 2020-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201024_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('AT', 'Austria'), ('IT', 'Italy'), ('BE', 'Belgium'), ('LV', 'Latvia'), ('BG', 'Bulgaria'), ('LT', 'Lithuania'), ('HR', 'Croatia'), ('LU', 'Luxembourg'), ('CY', 'Cyprus'), ('MT', 'Malta'), ('CZ', 'Czechia'), ('NL', 'Netherlands'), ('DK', 'Denmark'), ('PL', 'Poland'), ('EE', 'Estonia'), ('PT', 'Portugal'), ('FI', 'Finland'), ('RO', 'Romania'), ('FR', 'France'), ('SK', 'Slovakia'), ('DE', 'Germany'), ('SI', 'Slovenia'), ('GR', 'Greece'), ('ES', 'Spain'), ('HU', 'Hungary'), ('SE', 'Sweden'), ('IE', 'Ireland')], default='DE', max_length=2, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección fiscal'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tin',
            field=models.CharField(blank=True, max_length=32, unique=True, verbose_name='NIF'),
        ),
    ]
