# Generated by Django 3.0.5 on 2020-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201024_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('VI', 'Arava'), ('AB', 'Albacete'), ('A', 'Alacant'), ('AL', 'Almería'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('CS', 'Castelló'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('C', 'A Coruña'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Gipuzkoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('IB', 'Islas Baleares'), ('J', 'Jaén'), ('LR', 'La Rioja'), ('GC', 'Las Palmas'), ('LE', 'León'), ('L', 'Lleida'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('OU', 'Ourense'), ('O', 'Oviedo'), ('P', 'Palencia'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Santa Cruz de Tenerife'), ('S', 'Santander'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'València'), ('VA', 'Valladolid'), ('BI', 'Bizkaia'), ('ZA', 'Zamora'), ('Z', 'Zaragoza'), ('CE', 'Ceuta'), ('ML', 'Melilla')], default='L', max_length=2, verbose_name='Provincia'),
        ),
    ]
